//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anycmd.Xacml.Properties
{


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anycmd.Xacml.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bug!!! 的本地化字符串。
        /// </summary>
        internal static string exc_bug {
            get {
                return ResourceManager.GetString("exc_bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration file is not found 的本地化字符串。
        /// </summary>
        internal static string exc_configuration_file_not_found {
            get {
                return ResourceManager.GetString("exc_configuration_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate policy in repository. 的本地化字符串。
        /// </summary>
        internal static string exc_duplicated_policy_in_repository {
            get {
                return ResourceManager.GetString("exc_duplicated_policy_in_repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid attribute designator. 的本地化字符串。
        /// </summary>
        internal static string exc_invalid_attribute_designator {
            get {
                return ResourceManager.GetString("exc_invalid_attribute_designator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid datatype in parameter {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string exc_invalid_datatype_in_stringvalue {
            get {
                return ResourceManager.GetString("exc_invalid_datatype_in_stringvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid day-time duration value: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string exc_invalid_daytime_duration_value {
            get {
                return ResourceManager.GetString("exc_invalid_daytime_duration_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The document does not contain a Policy or PolicySet element. 的本地化字符串。
        /// </summary>
        internal static string exc_invalid_document_format_no_policyorpolicyset {
            get {
                return ResourceManager.GetString("exc_invalid_document_format_no_policyorpolicyset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function can&apos;t be used as a bag. 的本地化字符串。
        /// </summary>
        internal static string exc_invalid_function_usage {
            get {
                return ResourceManager.GetString("exc_invalid_function_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid node name &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string exc_invalid_node_name {
            get {
                return ResourceManager.GetString("exc_invalid_node_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If the stream can&apos;t be randomly positioned, please provide a version hint, since the document must be read twice to determine the version of the schema used. 的本地化字符串。
        /// </summary>
        internal static string exc_invalid_stream_parameter_canseek {
            get {
                return ResourceManager.GetString("exc_invalid_stream_parameter_canseek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Uri types, &quot;urn&quot; schema is supported only 的本地化字符串。
        /// </summary>
        internal static string exc_invalid_uri_schema {
            get {
                return ResourceManager.GetString("exc_invalid_uri_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid year-month duration value: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string exc_invalid_yearmonth_duration_value {
            get {
                return ResourceManager.GetString("exc_invalid_yearmonth_duration_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Policy reference id &apos;{0}&apos; not resolved 的本地化字符串。
        /// </summary>
        internal static string exc_policy_reference_not_resolved {
            get {
                return ResourceManager.GetString("exc_policy_reference_not_resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Policy set reference id &apos;{0}&apos; not resolved 的本地化字符串。
        /// </summary>
        internal static string exc_policyset_reference_not_resolved {
            get {
                return ResourceManager.GetString("exc_policyset_reference_not_resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type mismatch, expected:{0} contained:{1}. 的本地化字符串。
        /// </summary>
        internal static string exc_type_mismatch {
            get {
                return ResourceManager.GetString("exc_type_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported XPath version: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string exc_unsupported_xpath_version {
            get {
                return ResourceManager.GetString("exc_unsupported_xpath_version", resourceCulture);
            }
        }
    }
}
